backend = "glx";
vsync = true;

shadow = true;
shadow-radius = 12;
shadow-offset-x = -15;
shadow-offset-y = -15;
shadow-opacity = 0.3;

corner-radius = 12;
round-borders = 1;

blur-method = "dual_kawase";
blur-strength = 8;

fading = true;
fade-in-step = 0.03;
fade-out-step = 0.03;

# Añadimos opacidad para kitty (90%)
opacity-rule = [
  "60:class_g = 'Polybar'",
  "60:class_g = 'Rofi'",
  "50:class_g = 'kitty'"
];

# Blur solo para ventanas normales, no docks/notifications
blur-background-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'",
  "class_g = 'Notification'"
  # NO excluir kitty para que tenga blur
];
